# fly.toml app configuration file generated for macrolev on 2023-12-03T16:25:45+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "macrolev"
primary_region = "cdg"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  ENV = "production"
  PORT = "8080"
  TZ = "Europe/Paris"
  PUBLIC_URL = "macrolev.fly.dev"

[[service]]
  internal_port = 8080
  processes = [ "app" ]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1

  [[services.ports]]
    handlers = [ "http" ]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = [ "tls", "http" ]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
  