name: Deploy

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    defaults:
      run:
        working-directory: web-app

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: node-version
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: web-app/package-lock.json
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Generate SVG icons sprite
        run: npx tsx generate-svg-icons-sprite.ts
      - name: Build
        run: npm run build
      # https://github.com/remix-run/react-router/issues/12083
      - name: WORKAROUND for react-router and github pages
        run: |
          mv build/client/macrolev/* build/client/
          rmdir build/client/macrolev
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web-app/build/client'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
